### ISSUE TITLE
Is there a way to add captions?

### ISSUE THREAD

**Issue by senlin** [wottpal/kirby-lightbox-gallery#1]
Hi, pretty new to Kirby and just installed your plugin. 

Works awesome, but I'm wondering whether it is possible at all  to add captions of the images?

Happy Holidays!
Pieter

**Comment by wottpal** [comment]
Hi @senlin,
first: Happy Holidays!

Yes title & captions are very easy to add. You can add these two fields to your images: `title` and `caption` (in your blueprints, read more [here](https://getkirby.com/docs/panel/blueprints/file-settings#file-fields)). And the content will automatically be inserted into the `<figcaption>` tag and will be dynamically loaded into the Photoswipe-Caption :)

If you only want to display the title & caption in the Photoswipe-Lightbox and not under the thumbnails you can easily hide `<figcaption>` with CSS.

Dennis

**Comment by senlin** [comment]
Hi Dennis,
Thanks for your reply.

Thing is that I'm not using blueprints for the images I add to the gallery.

I have my Projects to which I want to add a gallery with screenshots.
So I have uploaded a couple of screenshots to the project and show them by inserting the following line in the content:

`(gallery: img1.jpg img2.jpg)`

I don't see how I can get a caption with this and I don't understand why I would need a blueprint for the images and even if I would need how I would add that then to the project?

Sorry bit confused now...

**Comment by wottpal** [comment]
Do you use the panel at all?

**Comment by senlin** [comment]
Ah, okay, I got it now. My project blueprint already contained `files`, so all I needed to do was to add the caption there according to the instructions you posted.

Many thanks!

Happy New Year!

**Comment by wottpal** [comment]
Nice! You too!
