### ISSUE TITLE
Feature Ideas/Requests

### ISSUE THREAD

**Issue by demlak** [wottpal/kirby-lightbox-gallery#6]
Hi, i saw this Gallery: http://topdevs.net/smart-grid-gallery/

i like those hover effects and caption styles, the image alignment of different image sizes and the animation -> fullscreen, when clicking on an image.

Maybe you are interested to implement such features?

thx a lot
demlak

**Comment by wottpal** [comment]
Hey @demlak, thanks for your suggestions :) But IMO this repo is more focused on the Kirby&Markup part of the gallery. The visual implementation (CSS) and JS is completely up to the developer. The JS/CSS shipped with the plugin should only be considered as a (already pretty nice) quick start.

**Comment by demlak** [comment]
thx.. but that's a pitty =)
